# Generated by Django 2.0.8 on 2018-09-06 00:27

import cosme.v1.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('cosmepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.COSMEPage')),
                ('header', wagtail.core.fields.StreamField([('info_unit', wagtail.core.blocks.StructBlock([('image', wagtail.core.blocks.StructBlock([('upload', wagtail.images.blocks.ImageChooserBlock(required=False)), ('alt', wagtail.core.blocks.CharBlock(help_text="If the image is decorative (i.e., if a screenreader wouldn't have anything useful to say about it), leave the Alt field blank.", required=False))])), ('heading', wagtail.core.blocks.StructBlock([('text', cosme.v1.blocks.HeadingTextBlock(required=False)), ('level', wagtail.core.blocks.ChoiceBlock(choices=[('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')])), ('icon', cosme.v1.blocks.HeadingIconBlock(help_text='Input the name of an icon to appear to the left of the heading. E.g., approved, help-round, etc. <a href="https://cfpb.github.io/capital-framework/components/cf-icons/#icons">See full list of icons</a>', required=False))], default={'level': 'h3'}, required=False)), ('body', wagtail.core.blocks.RichTextBlock(blank=True, required=False)), ('links', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=False)), ('url', wagtail.core.blocks.CharBlock(default='/', required=False))]), required=False))])), ('half_width_link_blob', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(label='H3 heading', required=False)), ('sub_heading', wagtail.core.blocks.CharBlock(label='H4 heading', required=False)), ('sub_heading_icon', wagtail.core.blocks.CharBlock(help_text='A list of icon names can be obtained at: https://cfpb.github.io/capital-framework/components/cf-icons/. Examples: linkedin-square, facebook-square, etc.', label='H4 heading icon', required=False)), ('body', wagtail.core.blocks.RichTextBlock(blank=True, required=False)), ('links', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=False)), ('url', wagtail.core.blocks.CharBlock(default='/', required=False))]), required=False))]))], blank=True)),
                ('latest_updates', wagtail.core.fields.StreamField([('posts', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('categories', wagtail.core.blocks.ChoiceBlock(choices=[('speech-bubble', 'Blog'), ('newspaper', 'Newsroom'), ('document', 'Report'), ('date', 'Events'), ('microphone', 'Speech'), ('bullhorn', 'Press release'), ('contract', 'Op-ed'), ('double-quote', 'Testimony')], required=False)), ('link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=False)), ('url', wagtail.core.blocks.CharBlock(default='/', required=False))])), ('date', wagtail.core.blocks.DateTimeBlock(required=False))])))], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('v1.cosmepage',),
        ),
    ]
